### ISSUE TITLE
Enable stratified sampling for Column level sampling

### ISSUE THREAD

**Issue by pramitchoudhary** [datascienceinc/Skater#123]
Lets see if we can add support for Stratified Sampling with the first release. This seems to be very important to me, what do you think @aikramer2.

**Comment by pramitchoudhary** [comment]
@aikramer2 did we already add support for it ? Can't remember from the top of my head.

**Comment by aikramer2** [comment]
A while back i reimplemented DataManager.generate_column_sample with:
```
def generate_column_sample(self, feature_id, *args, **kwargs):
        dm = DataManager(self[feature_id],
                         feature_names=[feature_id],
                         index=self.index)
        return dm.generate_sample(*args, **kwargs)
```

so all the sampling methods we provide for sampling an entire dataset are available at the column level. Closing this.
