### ISSUE TITLE
re-architect package to eliminate redundant code

### ISSUE THREAD

**Issue by aikramer2** [datascienceinc/Skater#127]
There are redundant tests, parts of pdp (especially early in the func), argument handling could be abstracted away in various components. This is multi day project and may motivate several new tickets.

**Comment by pramitchoudhary** [comment]
@aikramer2 as we have improved the code, do you feel the need to for this ticket ? If you agree them we can close this and open more specific one articulating the changes. What do u think ?

**Comment by pramitchoudhary** [comment]
@aikramer2 Closing this ticket. We do need re-structuring but lets specific ones as we will have to re-structure the code in stages. Doing all at once is too risky.
