### ISSUE TITLE
Provide distribution on Conda

### ISSUE THREAD

**Issue by aikramer2** [datascienceinc/Skater#135]

**Comment by benvandyke** [comment]
Submitted a PR to conda-forge: https://github.com/conda-forge/staged-recipes/pull/3092

**Comment by pramitchoudhary** [comment]
thanks @benvandyke

**Comment by aikramer2** [comment]
@benvandyke thanks for working this. I see that things look good on conda-forge. OK to close?

**Comment by benvandyke** [comment]
Sure, I'll submit another PR with documentation updates once the feedstock has been created and I've tested the install.

**Comment by pramitchoudhary** [comment]
Are we good to close this issue @benvandyke @aikramer2 ?

**Comment by pramitchoudhary** [comment]
thanks @benvandyke for looking into this
