### ISSUE TITLE
Class label in ensemble example

### ISSUE THREAD

**Issue by caterpillars** [datascienceinc/Skater#164]
In the ensemble example (https://github.com/datascienceinc/Skater/blob/master/examples/ensemble_model.ipynb). The output of pd.DataFrame(data.target_names) is:

0	malignant
1	benign

But the class label in the following code seems to be the opposite : 
exp = LimeTabularExplainer(X_test, 
                           feature_names=data.feature_names, 
                           discretize_continuous=False, 
                           class_names=['p(No Cancer)', 'p(Cancer)'])

Should the class names be switched?

Thanks

**Comment by aikramer2** [comment]
Ah good catch, I believe you're correct. If you'd like to submit a PR please do, otherwise I can fix the issue this weekend.

**Comment by caterpillars** [comment]
Thanks for confirming. I will close this issue for now.
