### ISSUE TITLE
plot_partial_dependence with Python 3

### ISSUE THREAD

**Issue by viticano** [datascienceinc/Skater#166]
I have a TooManyFeaturesError using plot_partial_dependence with Python 3 that does not occur with Python 2.
It seems to be caused by "hasattr(feature_or_feature_pair, '__iter__')" in the _check_features function (line 139 of partial_dependence.py). String are iterable with Python 3 but were not with Python 2.
Replacing this line by "not isinstance(feature_or_feature_pair, str)" should correct this.

**Comment by aikramer2** [comment]
https://github.com/datascienceinc/Skater/pull/167
