### ISSUE TITLE
Simplest way to use strings with local interpretation

### ISSUE THREAD

**Issue by reiinakano** [datascienceinc/Skater#176]
My input data is a Numpy array with string columns. Placing it in a LimeTabularExplainer results in an error. What is the best way to handle this?

**Comment by aikramer2** [comment]
Hey @reiinakano, thanks for the issue, can you copy and paste a snippet illustrating what you're doing?

**Comment by reiinakano** [comment]
Never mind, this https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20continuous%20and%20categorical%20features.html shows exactly what I want to do (categorical part)
