### ISSUE TITLE
Use original LIME package together with Skater

### ISSUE THREAD

**Issue by reiinakano** [datascienceinc/Skater#177]
Is there any way at all to use the original LIME package with Skater? Basically I need the global interpretation from Skater and the better maintained local interpretation from LIME

**Comment by aikramer2** [comment]
Hey @reiinakano. I think the short term solution is to sync the current LIME package to ours, which I can do tomorrow. Were considering other longer term options at the moment, as I'd like this package to evolve into a much larger model interpretation package. Can you elaborate on what you found to be problematic with the version of LIME tied to our package?

**Comment by reiinakano** [comment]
Nothing in particular right now, it's just that I prefer using the latest stable release of a package to avoid bugs as much as possible.

Alright then I guess we can just rely on you guys to always keep it in sync with upstream LIME :)

**Comment by pramitchoudhary** [comment]
@reiinakano we will make sure that our included version is stable, if there is any specific error that you are encountering, just file an issue and we will make sure, its taken care of. Also, checkout our roadmap to get more ideas on where we are headed. Thanks for supporting us :)

**Comment by aikramer2** [comment]
@reiinakano synced
