### ISSUE TITLE
Binary image classification with Dense(1) model output not intuitively supported with image explanation

### ISSUE THREAD

**Issue by CPapadim** [datascienceinc/Skater#179]
In lime_image.py the way labels are determined is by looking at a matrix of prediction probabilities.  When the output of the final layer is encoded in a single unit, with high activity meaning class 1 and low activity meaning class 0, the only label available using this approach will be label 0, even though the model returns either 0 or 1 as a class.

Relevant section of the code in lines 226 to 240 in that file show that the way that class labels are determined here is unintuitive.

This also means that using the `positive_only = True` argument when passing in an image of class 0 that the network classifies as class 0 actually highlights the 'not class 0' pixels rather than the 'class 0' pixels.  

We can still get the 'class 0' pixels by passing in `positive_only = False` and taking the negative mask that is returned but this is at best unintuitive, and there is no `negative_only = True` setting.

**Comment by aikramer2** [comment]
thanks for raising @CPapadim 

I would suggest adding an output_formatter to your model to make the final transformation, to the effect of [x, 1-x]. The problem (for now) is that its hard to distinguish regressions from classifiers if outputs are just a 1D vector of floats. The longer term solution is to bake this into the API, such that the user is explicit about whether its a regression model or a classification. I started this but havent gotten around to wrapping it up.

**Comment by pramitchoudhary** [comment]
@aikramer2 do we have an issue open for "user explicitly defines regression or a classification model ?
