### ISSUE TITLE
InMemoryModel incorrectly identifying output_type as 'multilabel indicator' resulting in ModelError: If using classifier without probability scores, unique_values cannot be None

### ISSUE THREAD

**Issue by reiinakano** [datascienceinc/Skater#189]
Code to reproduce:

```python
from sklearn.datasets import load_breast_cancer
from sklearn.neighbors import KNeighborsClassifier
from skater.model import InMemoryModel

X, y = load_breast_cancer(True)
X, y = X[15:40], y[15:40]
model = KNeighborsClassifier(weights='distance', p=2, n_neighbors=10).fit(X, y)
InMemoryModel(model.predict_proba, examples=X)
```
raises
```
skater.util.exceptions.ModelError: If using classifier without probability scores, unique_values cannot be None
```

Reason for this is when identifying output type, sklearn.utils.multiclass.type_of_target outputs "multilabel-indicator" because the output probabilities look like this:

```
array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.]])
```

In my use case, this happens often enough to bother me. Not sure how best to solve this, but I think one way is to allow the user to manually specify `output_type` when it is known.

If anyone can suggest a quick workaround while you fix this, it would be much appreciated. Thanks.

**Comment by aikramer2** [comment]
Hey @reiinakano, thanks for raising. This is caused by this issue:
https://github.com/datascienceinc/Skater/issues/161
Ill fix this up as soon as I can. In the mean time, I'm not sure theres a great workaround. You might try finding an example that would cause the model to return something other than 0 or 1, or setting model.probability = True (I think this might trigger an error though). I expect to have to fix tomorrow though.

**Comment by aikramer2** [comment]
@reiinakano this should now work:

```
from sklearn.datasets import load_breast_cancer
from sklearn.neighbors import KNeighborsClassifier
from skater.model import InMemoryModel

X, y = load_breast_cancer(True)
X, y = X[15:40], y[15:40]
model = KNeighborsClassifier(weights='distance', p=2, n_neighbors=10).fit(X, y)
InMemoryModel(model.predict_proba, examples=X, probability=True)
```

**Comment by lrq3000** [comment]
The probability keyword is not available anymore, I guess it has been deprecated and replaced with the `unique_values` keyword?
