### ISSUE TITLE
skater.util.exceptions.ModelError: Predict function must be callable

### ISSUE THREAD

**Issue by Nithanaroy** [datascienceinc/Skater#214]
Was checking out some examples in the documentation - https://datascienceinc.github.io/Skater/reference/interpretation.html#skater.core.global_interpretation.feature_importance.FeatureImportance.plot_feature_importance

```
from skater.model import InMemoryModel
    from skater.core.explanations import Interpretation
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.datasets import load_iris

    X, y = load_iris(True)
    rf = RandomForestClassifier()
    rf.fit(X,y)
    model = InMemoryModel(rf, examples = X)
    interpreter = Interpretation()
    interpreter.load_data(X)
    interpreter.feature_importance.plot_feature_importance(model, ascending=True, ax=None)
```

gave this error,

```
Traceback (most recent call last):
  File "rough.py", line 52, in <module>
    main()
  File "rough.py", line 48, in main
    model_interpration_skater()
  File "rough.py", line 40, in model_interpration_skater
    model = InMemoryModel(rf, examples = X)
  File "<ABS_PATH>/lib/python2.7/site-packages/skater/model/local_model.py", line 75, in __init__
    raise(exceptions.ModelError("Predict function must be callable"))
skater.util.exceptions.ModelError: Predict function must be callable
```

**Comment by aikramer2** [comment]
https://github.com/datascienceinc/Skater/pull/215
and https://github.com/datascienceinc/Skater/pull/216

**Comment by aikramer2** [comment]
@pramitchoudhary ^^

**Comment by pramitchoudhary** [comment]
thanks for looking into these guys. Merging the fixes @Nithanaroy @aikramer2

**Comment by pramitchoudhary** [comment]
Post merging PRs related to 214, this should be resolved right? ok to close this issue?

**Comment by Nithanaroy** [comment]
Thank you every one for addressing this.

Changing the code to what @pramitchoudhary suggested in the new doc, I am getting a `DataSet` error which I believe is not true.

```
from skater.model import InMemoryModel
from skater.core.explanations import Interpretation
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
import pandas as pd

X, y = load_iris(True)
X = pd.DataFrame(X)
rf = RandomForestClassifier()
rf.fit(X,y)
model = InMemoryModel(rf.predict_proba, examples = X)
interpreter = Interpretation()
interpreter.load_data(X)
interpreter.feature_importance.plot_feature_importance(model, ascending=True, ax=None)
```

gives the error,
```
---------------------------------------------------------------------------
DataSetError                              Traceback (most recent call last)
<ipython-input-7-c94f321c1a0f> in <module>()
      4 rf.fit(X,y)
      5 model = InMemoryModel(rf.predict_proba, examples = X)
----> 6 interpreter = Interpretation()
      7 interpreter.load_data(X)
      8 interpreter.feature_importance.plot_feature_importance(model, ascending=True, ax=None)

<SOME_ABS_PATH>/lib/python2.7/site-packages/skater/core/explanations.pyc in __init__(self, training_data, training_labels, feature_names, index, log_level)
     57                        training_labels=training_labels,
     58                        feature_names=feature_names,
---> 59                        index=index)
     60 
     61 

<SOME_ABS_PATH>/lib/python2.7/site-packages/skater/core/explanations.pyc in load_data(self, training_data, training_labels, feature_names, index)
     87                                     feature_names=feature_names,
     88                                     index=index,
---> 89                                     log_level=self._log_level)
     90         self.logger.info("Data loaded")
     91         self.logger.info("Data shape: {}".format(self.data_set.X.shape))

<SOME_ABS_PATH>/lib/python2.7/site-packages/skater/data/datamanager.pyc in __init__(self, X, y, feature_names, index, log_level)
    102         self.logger = build_logger(log_level, __name__)
    103 
--> 104         self.X = self._check_X(X)
    105         self.y = self._check_y(y, self.X)
    106         self.data_type = type(X)

<SOME_ABS_PATH>/lib/python2.7/site-packages/skater/data/datamanager.pyc in _check_X(self, X)
     33             err_msg = 'Invalid Data: expected data to be a numpy array or pandas dataframe but got ' \
     34                       '{}'.format(type(X))
---> 35             raise(exceptions.DataSetError(err_msg))
     36         ndim = len(X.shape)
     37         self.logger.debug("__init__ data.shape: {}".format(X.shape))

DataSetError: Invalid Data: expected data to be a numpy array or pandas dataframe but got <type 'NoneType'>
```

**Comment by pramitchoudhary** [comment]
Interesting, let me look into it and get back to you

**Comment by pramitchoudhary** [comment]
@Nithanaroy 
Try the below mentioned code, and see if it works on your end (tried on python3.6)


    from skater.model import InMemoryModel
    from skater.core.explanations import Interpretation
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.datasets import load_iris

    X, y = load_iris(True)
    rf = RandomForestClassifier()
    rf.fit(X, y)

    interpreter = Interpretation(X) 
    model = InMemoryModel(rf.predict_proba, examples=X)
    interpreter.feature_importance.plot_feature_importance(model, ascending=True)



**Note: if in Jupyter Notebook environment, remember to use %matplotlib inline

**Comment by gkjegan** [comment]
Hi, 

I tried the above code, i am getting 
TypeError                                 Traceback (most recent call last)
<ipython-input-35-3b1885b64e41> in <module>()
----> 1 plots = interpreter.feature_importance.plot_feature_importance(model, ascending = False)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/skater/core/global_interpretation/feature_importance.pyc in plot_feature_importance(self, modelinstance, filter_classes, ascending, ax, progressbar, n_jobs, n_samples, method, scorer_type, use_scaling)
    253                                               method=method,
    254                                               scorer_type=scorer_type,
--> 255                                               use_scaling=use_scaling)
    256 
    257         if ax is None:

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/skater/core/global_interpretation/feature_importance.pyc in feature_importance(self, model_instance, ascending, filter_classes, n_jobs, progressbar, n_samples, method, scorer_type, use_scaling)
     99                                                            include_y=True,
    100                                                            sample=True,
--> 101                                                            n_samples=n_samples)
    102         else:
    103             inputs, labels = self.data_set.X, self.data_set.y

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/skater/data/datamanager.pyc in generate_sample(self, sample, include_y, strategy, n_samples, replace, bin_count)
    422             ))
    423         if include_y:
--> 424             return self.__getrows__(idx), self._labels_by_index(idx)
    425         else:
    426             return self.__getrows__(idx)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/skater/data/datamanager.pyc in _labels_by_index(self, data_index)
    467 
    468         # do we need to coerce labels to a particular data type?
--> 469         return self.y[numeric_index]

TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by pramitchoudhary** [comment]
@gkjegan can you try with python3.6?

**Comment by gkjegan** [comment]
Failing at same line of code, but with the slightly different message for python 3.6
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-3b1885b64e41> in <module>()
----> 1 plots = interpreter.feature_importance.plot_feature_importance(model, ascending = False)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/skater/core/global_interpretation/feature_importance.py in plot_feature_importance(self, modelinstance, filter_classes, ascending, ax, progressbar, n_jobs, n_samples, method, scorer_type, use_scaling)
    253                                               method=method,
    254                                               scorer_type=scorer_type,
--> 255                                               use_scaling=use_scaling)
    256 
    257         if ax is None:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/skater/core/global_interpretation/feature_importance.py in feature_importance(self, model_instance, ascending, filter_classes, n_jobs, progressbar, n_samples, method, scorer_type, use_scaling)
     99                                                            include_y=True,
    100                                                            sample=True,
--> 101                                                            n_samples=n_samples)
    102         else:
    103             inputs, labels = self.data_set.X, self.data_set.y

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/skater/data/datamanager.py in generate_sample(self, sample, include_y, strategy, n_samples, replace, bin_count)
    422             ))
    423         if include_y:
--> 424             return self.__getrows__(idx), self._labels_by_index(idx)
    425         else:
    426             return self.__getrows__(idx)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/skater/data/datamanager.py in _labels_by_index(self, data_index)
    465 
    466         # do we need to coerce labels to a particular data type?
--> 467         return self.y[numeric_index]

TypeError: 'NoneType' object is not subscriptable

**Comment by pramitchoudhary** [comment]
@gkjegan, tried the code on a fresh install with python3.6 and skater==1.0.4/1.1.0b1. Everything worked fine. Possible to check on the python installation. Recommended one is from conda
`conda install python=3.6`

**Comment by pramitchoudhary** [comment]
I guessing things work with the new release guys. Closing this issue for now, if things still don't work for some reason, then let's open a new bug.
