### ISSUE TITLE
Can't pip install 1.0.3

### ISSUE THREAD

**Issue by CPapadim** [datascienceinc/Skater#219]
This version is listed as latest on pypi, but I get this when I try to install it:

`Could not find a version that satisfies the requirement skater==1.0.3 (from versions: 1.0.0b10, 1.0.0b11, 1.0.1, 1.0.2, 1.1.0b1)`

1.0.2 installs just fine (and also installs by default with `pip install skater`)

**Comment by pramitchoudhary** [comment]
@CPapadim thanks for reporting.  Let check and get back to you. 
Try the latest beta version for the time being, `sudo pip install -U --no-deps --force-reinstall skater==1.1.0b1` ( _This has the latest features_ )

**Comment by pramitchoudhary** [comment]
@CPapadim I just tried installing v1.0.3 on ubuntu x86_64 16.04.4 LTS(xenial), it installed fine for me.
`sudo pip install -U --no-deps --force-reinstall skater==1.0.3`.

**Comment by pramitchoudhary** [comment]
@johnchuckcase haven't tried on Mac, investigating. In the meantime, can you try `sudo pip install -U --no-deps --force-reinstall skater==1.1.0b1` on an ubuntu box, if possible?

**Comment by pramitchoudhary** [comment]
@johnchuckcaseI just tried `pip install skater==1.0.3` and `pip install ../skater-1.0.3-py2-none-any.whl` on mac using python2.7.9, they both worked fine.
Are you able to see the v1.0.3 here https://pypi.org/project/skater/#files?

**Comment by aikramer2** [comment]
@pramitchoudhary historically we've released source packages; looks like 1.0.3 is distributed as a wheel, and therefore will only work on the specified platforms.

**Comment by pramitchoudhary** [comment]
@aikramer2 ya agreed. Are you able to install v1.0.3 or is something wrong somewhere? I tried a couple of times and things seem all good at my end

**Comment by CPapadim** [comment]
Also this was with Python 3 so not sure if that's why.  I hope you guys are supporting Python 3

**Comment by pramitchoudhary** [comment]
@CPapadim I tried installing on a different Mac as well and executing `sudo pip install --user skater==1.0.3` worked just fine. Yes, we do support python3.5, python3.6, and python2.7. Would also suggest using conda to install python version. Depending on how the system is set up, there might be an issue with the pip version as well. To make sure right pip version is selected for installation, one can also try
`python -m pip install --user skater==1.0.3` or `python -m pip install --user skater==1.1.0b1
Would recommend using the latest version though `skater==1.1.0b1`

**Comment by CPapadim** [comment]
I'm installing python with Miniconda, I also tried upgrading pip, and using your various commands, none of it can find version 1.0.3.  My setup is pretty minimal - the default xenial_base dockerenv, and installing python with Miniconda.

Is 1.1.0b1 stable?  Pypi suggests not

**Comment by pramitchoudhary** [comment]
Thanks, @aikramer2. can we remove 1.0.3 as well?

**Comment by CPapadim** [comment]
Thanks, looks like 1.0.4 works

**Comment by pramitchoudhary** [comment]
thanks, guys @CPapadim @aikramer2

**Comment by code-dreamer-broker** [comment]
> @CPapadim @pramitchoudhary @johnchuckcase
> Alright, just released a source distribution to pypi; note that due to the idiosyncrasies of pypi, we had to bump the version. `pip install skater==1.0.4`. It is identical to 1.0.3

thanks a lot , `pip install skater==1.0.4`  its working for me
