### ISSUE TITLE
DataManager does not work with Pandas Dataframe

### ISSUE THREAD

**Issue by bacook17** [datascienceinc/Skater#241]
When a DataManager is loaded with a Pandas DataFrame, calls to the "feature_info" property raise a ValueError. It comes from generate_column_sample creating individual DataManagers for each column, which are Pandas Series, not DataFrames.

I am adding a pull-request which updates test_data.py to include a failing test, and will work on a correction.

**Comment by bacook17** [comment]
Corrected in #242

**Comment by pramitchoudhary** [comment]
#242 has been addressed and merged. Thanks again for the help @bacook17
